name: CI/CD Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4. Compila el proyecto
      - name: Build app
        run: npm run build

      # 5. Inicia sesión en DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Construye la imagen
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pokemon-backend:latest .

      # 7. Publica la imagen en DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pokemon-backend:latest
